@extends('layouts.site')

@section ('content')

  <article class="destination">
<figure class="destination-figure">
<img alt="Iguazú" class="afterload destination-image" data-original="{{ asset('images/destinations/iguazu.jpg') }}" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEHAAEALAAAAAABAAEAAAICTAEAOw==" title="Iguazú">
<figcaption class="hidden">
Iguazú
</figcaption>
</figure>
<h1 class="destination-title">Iguazú: Información turistica</h1>
<div class="destination-content">
<p>Dueña del extremo norte de la provincia de Misiones, la ciudad de <strong>Puerto Iguazú</strong> conforma la región de las Aguas Grandes engalanada con los paisajes más encantadores y apasionantes que la naturaleza pudo haberle concedido. Majestuosos saltos de agua, colores incomparables, exuberante vegetación, fauna increíblemente variada, melodías naturales, y mucho más, este edén de Argentina es digno de ser visitado por todos y en todo momento.</p>
<p><strong>Puerto Iguazú</strong> se sitúa en proximidades a la desembocadura del río homónimo favorecida por su vinculación con Brasil a través del Puente Internacional "Tancredo Neves", lo que sumado a sus privilegios naturales, ha motivado en ella el desarrollo de una importante infraestructura turística. Amplia gama de servicios de alojamiento, variado menú de cocina regional e internacional, centros de compra y una gran movida nocturna, todo armonizado por el clima subtropical húmedo característico de la zona, permiten la placentera estadía de los visitantes confirmando el posicionamiento de esta ciudad como centro turístico por excelencia.</p>
<p><strong>Puerto Iguazú</strong> es una de esas regiones privilegiadas del planeta. Un clima subtropical que no llega a martirizar, un inmenso Parque Nacional que cobija una increíble serie de exóticas plantas y animales, y unas maravillosas caídas de agua que asombran al hombre desde los albores de la humanidad.</p>
<p>Su principal atractivo, las Cataratas del Iguazú, un paraíso terrenal que agota las tonalidades de verdes y rojizos dibujando paisajes imponentes, atrae inevitablemente a todo turista que pise suelo misionero, invitándolo a recorrer sus pasarelas especialmente preparadas para el descubrimiento de cada rincón. Localizadas en el Parque Nacional Iguazú, una de las primeras áreas protegidas de América, las cataratas resguardan la reserva de fauna y flora más importante del país y una de las más ricas del mundo en cuanto a su biodiversidad, constituyéndose como un espacio que ningún amante de la naturaleza puede dejar de conocer.</p>
<p>Aventura, cultura y naturaleza encuentran su espacio ideal de realización en esta localidad de la provincia de Misiones, abarcando las más diversas actividades y convirtiendo las vacaciones en la región en una indescriptible vivencia de sensaciones.</p>
<h2 class="destination-subtitle">Atractivos Turísticos:</h2>
<p>Cataratas del Iguazú, Parque Nacional Iguazú, Hito Tres Fronteras, Represa de Itaipú. Reducciones Jesuíticas de San Ignacio.</p>
<h2 class="destination-subtitle">Cataratas del Iguazú</h2>
<p>Las Cataratas del Iguazú (en lengua guarani: Yguazu, en portugués: Cataratas do Iguaçú, ) son las cataratas localizadas en la frontera entre la provincia de Misiones, en el Parque Nacional Iguazú, Argentina y en el Parque Nacional do Iguazú en el estado de Paraná, Brasil. Están formadas por 275 saltos de hasta 70 metros de altura, alimentados por el caudal del río Iguazú . Se pueden realizar paseos en lancha bajo los saltos y caminatas por senderos apreciando algunos animales de la selva subtropical. La "Garganta del Diablo" es un espectáculo aparte que, saliendo desde Puerto Canoas , se puede disfrutar en toda su majestuosidad a tan sólo 50 de distancia.</p>
<h2 class="destination-subtitle">Paseo inferior</h2>
<p>Partiendo desde el mirador, que recuerda por su figura a un faro y se destaca del entorno por su color blanco, se desciende por numerosas escalinatas (algunas fueron talladas en la misma roca) hacia el río Iguazú y se transita por un bello sendero pedestre. Rodeado por la exuberante selva podrá disfrutar de una hermosa visión de la parte inferior de los saltos.</p>
<p>Comenzando la visita en el salto Lanusse y pasando por el Álvar Núñez Cabeza de Vaca, llegará a un espléndido punto panorámico desde donde tendrá una primera vista de la Garganta del Diablo. Avanzando un poco más se observa la isla San Martín y a su derecha el salto homónimo. Al final del sendero se encuentra el salto Bossetti. Si permanecemos largo tiempo terminaremos mojados, pues allí el vapor de agua producido por el choque del agua contra las rocas forma una tenue pero incesante lluvia. Descendiendo por el sendero hacia Punta Peligro podrá, si en ese momento se encuentra habilitado, navegar por el río Iguazú y cruzar a la isla San Martín. Ya de regreso se pasa por el salto Dos Hermanas, donde se puede gozar de un refrescante baño en la enorme pileta natural que se forma en su base.</p>
<h2 class="destination-subtitle">Paseo superior.</h2>
<p>Partiendo desde el mismo sitio antes mencionado, recorrerá, como el nombre del paseo indica, la parte superior de las caídas de agua. El punto de observación desde un nivel más alto cambia por completo la visión del paisaje. Verá prácticamente a sus pies despeñarse las turbulentas aguas. De esta manera visitará nuevamente el salto Dos Hermanas, el Bossetti, el Chico, que serán un pequeño adelanto de la imponente Garganta del Diablo. En este sitio, donde el agua cae desde aproximadamente 70 metros de altura, nos sorprenderá el ensordecedor bramar del agua, permanentemente cubiertas por densas columnas de vapor, que despide el choque del agua con las rocas.</p>
<p>Además de estos circuitos, se puede pasear en el ``tren ecológico´´, que recorre la selva. En uno de los accesos al parque (el más cercano al aeropuerto internacional) se encuentra un anfiteatro, un museo con información de la selva y de la historia de la provincia, sanitarios, primeros auxilios, restaurantes, pizzerías y kioscos (los tres últimos se pueden encontrar en algunos senderos en la selva).</p>
<p>En 1984 el sector argentino de las Cataratas, el Parque Nacional Iguazú, fue declarado Patrimonio de la Humanidad por la UNESCO. Posteriormente en 1986, el sector de Brasil, que se encuentra en el Parque Nacional do Iguaçu, también fue declarado Patrimonio de la Humanidad. Las cataratas lindan con Argentina y Brasil , y están a pocos kilómetros de la triple frontera con Paraguay.</p>
<p>Cerca de las Cataratas, se encuentra <strong>Puerto Iguazú</strong>, en la confluencia de los ríos Iguazú y Paraná, hacia las coordenadas 25°36'05"S, 54°34'07"O.</p>
<p>Las cataratas son el principal centro turístico del norte de Argentina , y uno de los principales de todo el país.</p>
<p>Estas gigantescas cataratas fueron descubiertas para los europeos a mediados del s XVI por la expedición española que comandaba Álvar Núñez Cabeza de Vaca marchando desde La Vera - más exactamente desde la isla de Santa Catarina - hacia Asunción del Paraguay; Cabeza de Vaca les llamó "saltos de Santa María".</p>
<h2 class="destination-subtitle">Parque Nacional Iguazú</h2>
<p>El Parque Nacional Iguazú fue creado en Argentina en el año 1934 con el objetivo de conservar las Cataratas del Iguazú, así como la biodiversidad que las rodea. Emplazado en el norte de la provincia de Misiones, cuenta con una superficie aproximada de 67.000 ha, y se encuentra a 17 km de <strong>Puerto Iguazú</strong>. La región altoparanaense, en la cual se encuentra el Parque Nacional Iguazú, muestra signos de habitación por parte del hombre que se remontan a más de 10.000 años. Se estima que alrededor del año 1000 DC los guaraníes, provenientes del norte, irrumpieron en la región y desplazaron a los nativos que se hallaban allí en ese entonces. En el momento de la llegada de los españoles al lugar, en el siglo XVI, los guaraníes estaban ampliando su territorio. Estos nativos se caracterizaban entre otras cosas por sus diversos cultivos.</p>
<p>Fue en 1542 cuando el primer europeo llegó a las cataratas. Fue Álvar Núñez Cabeza de Vaca, y las bautizó en ese entonces como "Saltos de Santa María". Hacia 1609 , se establecieron en la región las primeras misiones jesuíticas, las cuales permanecieron en el lugar durante más de un siglo y medio: la principal de las reducciones o ciudades misionales fue Santa María del Iguazú, de soberanía española. Su emplazamiento es prácticamente el mismo que el de la actualmente ciudad brasileña de Foz do Iguaçu.</p>
<p>A fines del siglo XIX llegó la primera expedición turística al lugar. Entre sus integrantes se contaba Victoria Aguirre, quien donó los fondos con los cuales se empezó a construir el acceso que va desde <strong>Puerto Iguazú</strong> (llamado a inicios del siglo XX Puerto Aguirre) hasta las cataratas.</p>
<p>En 1902, el Ministerio del Interior de Argentina encargó a Carlos Thays un relevamiento detallado de las cataratas, el cual se tomó como base posteriormente para la ley de creación del parque nacional.</p>
<h2 class="destination-subtitle">Recursos naturales</h2>
<p>Las cataratas se encuentran sobre el Río Iguazú, que tiene una longitud total de 1.230 km hasta su desembocadura en el Río Paraná. Dicha confluencia se encuentra a 23 km aguas abajo de las cataratas. Si bien el río tiene un ancho que suele estar entre los 500 m y los 1000 m a lo largo de todo su recorrido, en la zona del Parque Nacional se ensancha hasta alcanzar los 1500 m.</p>
<p>Tanto sobre las márgenes del río como en las numerosas islas del delta que se forma, crecen varias especies de árboles que se caracterizan por su requerimiento de humedad: el curupay, el laurel blanco, el mbarayú o cedro paranaense, el aguay y el ceibo (cuya flor es la flor nacional argentina) son algunas de ellas.</p>
<p>El clima de la zona permite que convivan bosques de curupay con numerosos pastizales, combinación que se da únicamente en esta zona del país. En su conjunto, la flora arbórea del Parque Nacional Iguazú está compuesta por más de 90 especies, siendo características del lugar las comunidades de palmito y palo rosa o perobá. Este último es un árbol que puede alcanzar hasta 40 m de altura, y a cuya sombra crecen los palmitos, palmeras cuyos troncos terminan en un cogollo comestible.</p>
<p>Entre las principales especies de aves que habitan en el lugar, debe citarse los vencejos de cascada, que vuelan atravesando los intersticios de las columnas de agua para posarse sobre la pared rocosa, donde muchas veces anidan.</p>
<p>En el sector de las pasarelas no es extraño encontrar coatíes y ejemplares del Tucán Grande, una de las cinco especies de tucanes que hay en el Parque, también se destaca el águila arpía.</p>
<p>En las partes soleadas de los senderos, y especialmente hacia el mediodía, se pueden apreciar ejemplares de lagartijas, del género Tropidurus, trepando troncos y piedras.</p>
<p>Entre las especies en peligro de extinción que se albergan en el Parque, deben citarse el yaguareté, el tapir-también conocido en la zona como: mbeorí-, el ocelote, el yaguarundí, el oso hormiguero-, las águilas selváticas y el yacaré overo.</p>
<h2 class="destination-subtitle">Reducciones Jesuiticas de Santa Ana:</h2>
<p>Estas Ruinas se encuentran ubicadas en la localidad de Santa Ana a 40 kilómetros de la ciudad de Posadas. La primera reducción de Santa Ana se fundó en 1633, en el actual territorio Ríograndense, de Brasil, para luego emigrar por la acción arrasadora de los bandeirantes. Más de 2.000 guaraníes de la primitiva reducción, junto, con los religiosos Romero y Agustín Contreras se afincaron definitivamente en el actual emplazamiento, en 1660. A pesar del avance de la selva, se puede apreciar la plaza central, la iglesia, las viviendas, los talleres y el cementerio, utilizado Por los Primeros pobladores de la localidad de Santa Ana. También se puede advertir lo que fue la estructura productiva de esta reducción con sus aguadas, solares, huerto y sistema de riego escalonado.</p>
<h2 class="destination-subtitle">Hito Tres Fronteras</h2>
<p>El Hito Tres Fronteras es un lugar turístico, ubicado en la ciudad de <strong>Puerto Iguazú</strong>, Misiones, Argentina . Se encuentra en la confluencia de los ríos Iguazú . Desde el lugar se pueden observar los tres países, y en cada uno de ellos, existe un obelisco pintado con los colores nacionales de Argentina, Brasil y Paraguay.</p>
<p>En el lugar, existe una Feria de Artesanos, donde se pueden comprar artesanías típicas de la provincia. También se logra observar, el puente Tancredo Neves, que conecta la ciudad argentina de <strong>Puerto Iguazú</strong> y su vecina brasileña de Foz do Iguazú. El lugar se encuentra dentro de la subregión turística de Región de las Aguas Grandes.</p>
<h2 class="destination-subtitle">Represa de Itaipú</h2>
<p>La Represa Hidroeléctrica de Itaipú (del guaraní, "piedra que canta"), la primera en tamaño en operación del mundo, es un emprendimiento binacional entre Brasil y Paraguay. Está ubicada sobre el río Paraná en la frontera entre estos dos países, en la ciudad de Hernandarias, a 14 km al norte del Puente de la Amistad.</p>
<h2 class="destination-subtitle">Reducciones Jesuíticas de San Ignacio</h2>
<p>Las ruinas de la reducción de San Ignacio Miní, una misión jesuítica fundada a comienzos del siglo XVII para evangelizar a los nativos guaraníes, se encuentran en la actual localidad de San Ignacio, en la provincia de Misiones, distantes unos 60 km de la capital provincial, Posadas.</p>
<p>La misión original fue erigida por los sacerdotes José Cataldino y Simón Maceta en la región que los nativos llamaban Guayrá y los españoles llamaron La Pinería, en el actual estado de Paraná Brasil, alrededor de 1610. En 1631, la mayor parte de las reducciones fueron asediadas y destruidas por los bandeirantes paulistas o mamelucos. Sólo las de San Ignacio y Nuestra Señora de Loreto resistieron los ataques, pero en 1632 decidieron trasladarse a la región de Paranaimá, hacia el oeste. Pese a la organización de milicias nativas organizadas y entrenadas por los jesuitas de vocación militar, las hostilidades obligaron a replegarse nuevamente hacia el este, a su ubicación actual, en donde en 1696, tras haber tenido diversos emplazamientos que fueron abandonados más tarde, se reestableció definitivamente. Recibió entonces el nombre de San Ignacio Miní ("la menor", en guaraní)para distinguirla de la anterior San Ignacio de la zona, llamada luego San Ignacio Guazú ("la mayor").</p>
<p>Hacia mediados del siglo XVIII la misión contaba con más de tres mil habitantes, y una rica e intensa actividad artesanal y cultural; su ubicación sobre el río Paraná favorecía el comercio con otros asentamientos de la zona. Sin embargo, en 1768, tras la expulsión de los jesuitas, fue abandonada por completo.</p>
<p>En la actualidad San Ignacio Miní es la mejor conservada de las misiones en territorio argentino. La planta de la misión es la común a la mayoría de las construidas por los jesuitas en la época: alrededor de una plaza central se distribuyen la iglesia, la Casa de los Padres, el cementerio, las viviendas y el cabildo. En la construcción de San Ignacio se empleó la piedra local, el asperón rojo, en grandes piezas. La dimensión de los trabajos ha permitido que, pese a años de deterioro, la mayor parte de los muros siga en pie.</p>
<p>Las Ruinas Jesuíticas de la Misión de San Ignacio Miní, junto con las de Nuestra Señora de Loreto, Santa Ana y Santa María la Mayor (actualmente en Argentina) y São Miguel (Brasil) fueron declaradas Patrimonio Mundial de la Humanidad por la UNESCO en 1984. Las de Santísima Trinidad y Jesús, en Paraguay , fueron declaradas Patrimonio de la Humanidad en 1993.</p>
</div>
</article>
@endsection