@extends('layouts.site')

@section ('content')

  <article class="destination">
<figure class="destination-figure">
<img alt="Ushuaia" class="afterload destination-image" data-original="{{ asset('images/destinations/ushuaia.jpg') }}" src="data:image/gif;base64,R0lGODlhAQABAIAAAP///////yH5BAEHAAEALAAAAAABAAEAAAICTAEAOw==" title="Ushuaia">
<figcaption class="hidden">
Ushuaia
</figcaption>
</figure>
<h1 class="destination-title">Ushuaia: Información turistica</h1>
<div class="destination-content">
<p>La ciudad más austral del mundo, <strong>Ushuaia</strong>, es la puerta de ingreso a la Antártida, el punto de convergencia de montañas, glaciares, bosques y mar, es la capital de la provincia argentina de Tierra del Fuego, Antártida e Islas del Atlántico Sur.</p>
<p><strong>Ushuaia</strong>, no es sólo una pequeña y pintoresca ciudad en el extremo del mundo o una sencilla bahía de singular belleza protegida por los vientos, <strong>Ushuaia</strong> es la naturaleza y la aventura en su máxima expresión.</p>
<p>En ella el viajero tendrá amplísimas posibilidades para vivir un verano inolvidable o el más crudo invierno cerca de la Antártida.</p>
<p>Turismo de aventura, trekking, cabalgatas, pesca deportiva o mountain-bike; recorridos hacia lugares inexplorados, paseos en barco, en los que modernos catamaranes o confortables veleros, lo llevarán por el Canal de Beagle hasta el Cabo de Hornos y el Continente Antártico.</p>
<p>Singularmente pintoresca, con sus antiguas casas de madera y chapa metálica que muestran techos de marcado declive para evitar la acumulación de nieve, <strong>Ushuaia</strong> refleja en su trazo urbano y sus diseños arquitectónicos una fuerte conexión con su pasado.</p>
<p>Con un ayer signado por navegantes europeos, cazadores de indios, buscadores de oro y un presidio de triste fama, la ciudad presenta hoy al viajero distintas maneras de conocer esa historia. <strong>Ushuaia</strong>, no es sólo una pequeña ciudad en el extremo del mundo, o una sencilla bahía de singular belleza protegida por los vientos, <strong>Ushuaia</strong> es la naturaleza y la aventura en su máxima expresión.</p>
<p>La caprichosa topografía ha generado una ciudad que combina colores y desniveles que se acompaña con la silueta de los Andes, una silueta que se recorta contra el firmamento y ofrece a los visitantes un marco de paisajes imponentes, con un puerto natural de aguas profundas y hermosos lugares completamente vírgenes a pocos minutos del centro urbano.</p>
<p>La ciudad cuenta con una muy buena infraestructura hotelera y gastronómica, en donde se puede degustar la tradicional centolla fueguina, la merluza negra, el abadejo y el besugo, exquisitos mariscos, como así también el cordero patagónico a la cruz.</p>
<p>Su gente, sus orígenes, su mística y su naturaleza se descubren en la danza, la pintura, la cerámica, las artesanías, la fotografía y el teatro; actividades que se realizan en centros culturales o salas de espectáculos.</p>
<p>En el casco histórico, espacio que aún mantiene las viejas calles originarias de la ciudad, perduran varios ejemplos de construcciones originales, Monumentos, Parques e Iglesias.</p>
<p>En <strong>Ushuaia</strong> la temperatura media anual es de unos 5° C y los extremas son 29° C y -21° C. Los meses más fríos son Julio y Agosto; la temperatura baja mucho de Junio a Septiembre pero en las regiones húmedas del Oeste es muy raro que hiele.</p>
<p>Actualmente <strong>Ushuaia</strong> tiene una población de 44.976 habitantes.</p>
<h2 class="destination-subtitle">Atractivos Turísticos:</h2>
<p>Costanera, Parque Nacional Tierra del Fuego, Canal de Beagle, Lagos Escondido y Fagnano, Tren del Fin del Mundo, Isla de los Lobos e Isla de Los Pajaros.</p>
<h2 class="destination-subtitle">Costanera</h2>
<p>Valiosa vista para apreciar el Estrcho de Magallanes que comprende desde la calle Manuel Señoret y Santa María, donde encontramos la Plaza de las Banderas, el Parque Croata y el Parque del Recuerdo, que reúne una interesante muestra de maquinarias que datan de la década del 1900, en el lugar se destaca el Monumento Selk'nam confeccionado en madera natural y se ubica la casa donde funcionó el Primer Cine de Tierra del Fuego. también se pueden visitar los kioscos donde se ofrece artesanía local.</p>
<h2 class="destination-subtitle">Parque Nacional Tierra del Fuego</h2>
<p>Creado por el Gobierno Argentino en el año 1960 para proteger la porción más austral de bosques subantárticos, el Parque Nacional Tierra del Fuego es el único del país que posee costa marítima como uno de sus límites naturales. Brinda atractivos históricos y silvestres, limitando al oeste con Chile y al sur con el Canal de Beagle.</p>
<p>Con una superficie de 63,000 hectáreas, está ubicado en el sector sudoeste de Tierra del Fuego, sobre el límite internacional con Chile. De relieve montañoso, presenta un típico paisaje glacial, que se alterna con profundos valles bañados por ríos y lagos y cordones montañosos orientados de noroeste a sudeste.</p>
<p>En el sector costero, las Bahías Lapataia y Ensenada intercalan barrancos y pequeñas playas que constituyen el ambiente ideal para la avifauna costera. Los bosques de lengas y guindos abarcan las áreas más húmedas y la costa del Canal de Beagle. Durante la primavera abundan las orquídeas de Magallanes, el michay, que abre sus flores amarillas, y los hongos en polvera.</p>
<p>El Parque Nacional cuenta con senderos peatonales que parten desde diferentes puntos de la Ruta Nacional N° 3 y permiten llegar a maravillosos lugares:</p>
<p><strong>Paseo de la Isla</strong>: A través de 800 metros, recorre el archipiélago Cormoranes y transita por las costas del Río Lapataia y Ovando.</p>
<p><strong>Paseo a la Laguna Negra</strong>: Se encuentra a 400 metros del Parque. Sus aguas presentan una coloración oscura debido a la presencia de extensos turbales.</p>
<p><strong>Paseo al mirador</strong>: Luego de 500 metros se accede a Bahía Lapataia a través de bosques de lengas. Desde el mirador se obtiene una vista panorámica de la Bahía.</p>
<p><strong>Paseo del turbal</strong>: Queda a 400 metros de Bahía Lapataia. En el camino, recorrerán bosques de lengas y una castorera abandonada en la que se observa el sistema de diques construido por estos roedores.</p>
<p>Para realizar recorridos de mayor duración, esta área protegida ofrece varias alternativas:</p>
<p><strong>Senda Pampa Alta</strong>: Conecta los campamentos del Río Pipo y Ensenada. Se recorren bosques de lenga y guindo. En Pampa Alta se obtiene una vista panorámica del Canal de Beagle. Es un recorrido de 5 kilómetros.</p>
<p><strong>Senda Costera</strong>: Une el campamento de Ensenada con el sector Lapataia. Se conoce la costa marina en las Bahías Lapataia y Ensenada. El recorrido es de 8 kilómetros.</p>
<p><strong>Senda al Hito XXIV</strong>: Se transita la costa norte del Lago Roca, de origen glaciario. El recorrido es de 10 kilómetros.</p>
<p><strong>Senda al Cerro Guanaco</strong>: Se asciende por una picada de pendiente muy pronunciada. El recorrido es de 8 kilómetros y la altura del cerro es de 970 metros.</p>
<h2 class="destination-subtitle">Canal de Beagle</h2>
<p>La ciudad austral de <strong>Ushuaia</strong>, ubicada a orilla del Canal Beagle y rodeada por los montes Martial, ofrece en el país un paisaje único combinando montañas, mar y bosques.</p>
<p>Como los primeros exploradores, uno puede navegar y disfrutar el Canal Beagle que, con sus bahías, islotes y rica avifauna merece sinceramente ser visitado. Se puede recorrer dicho canal optando entre una amplia variedad de embarcaciones, desde modernos catamaranes, confortables motonaves o motoveleros, además de botes neumáticos y veleros. Si bien todos recorren las cristalinas aguas del Canal Beagle, cada propuesta se diferencia por características particulares. Guías bilingües y experimentados transmiten sus conocimientos sobre la fauna y flora de la región, sus primeros habitantes y en algunos casos, si las condiciones climáticas lo permiten, serán los responsables de guiar a los turistas en una enriquecedora caminata por alguna de las islas o islotes del canal, que custodian estas aguas.</p>
<p>Por lo general se parte de <strong>Ushuaia</strong> y se ingresa al Canal Beagle, visitando la Isla de los Pájaros con sus lobos marinos e interesantísima fauna, y el Faro Les Eclaireurs, donde se observan los restos del buque Monte Cervantes, hundido en 1930. Se continúa a la Estancia Remolino, construida en 1890 perteneció a la familia británica Lawrence, donde se observan los restos del buque Sarmiento, hundido en 1912.</p>
<p>Luego se llega a Bahía Brown y Puerto Almanza, por los pasos Ara Guaraní en la Grande y Mackinlay hacia el sur. La navegación sigue por las costas de las Islas Gable y Grande. Más adelante la Bahía Haberton y el casco de la estancia del mismo nombre, perteneciente a los descendientes del misionero anglicano Thomas Bridges, desde donde se realiza una caminata guiada por la primera estancia de Tierra del Fuego. Finalmente se observa la Isla Martillo (Yecapasela), con sus hermosos pingüinos magallánicos, y se regresa a <strong>Ushuaia</strong>.</p>
<p>La duración de la salida es aproximadamente de siete a ocho horas como mínimo, llegando a durar más de un día en algunos casos.</p>
<p>La transparencia de las aguas, con el agregado de la naturaleza que las rodea, la abundancia de cormoranes, pingüinos, gaviotas, golondrinas y mamíferos que habitan las aguas, son todos elementos que harán que al turista le resulte una experiencia inolvidable el haber viajado hasta estos lugares.</p>
<p>Hay también excursiones menos extensas, que también salen de la Bahía de <strong>Ushuaia</strong>, y llegan a Paso Chico, Islas Bridge, Isla de los Lobos, Isla de los Pájaros y Faro Les Eclaireurs, donde se observan los restos del naufragio ocurrido en 1930 del buque de origen alemán Monte Cervantes, que duran de tres a cuatro horas aproximadamente.</p>
<p>En todas las excursiones por el Canal Beagle se disfruta de una interesante vista panorámica de la ciudad de <strong>Ushuaia</strong>.</p>
<h2 class="destination-subtitle">Lagos Escondido y Fagnano</h2>
<p>Pintoresco lugar de singular belleza. En él, la Hostería Petrel con sus cabañas ubicadas a la orilla de este lago, ofrece gran comodidad para pernoctar y saborear deliciosos platos regionales. En este lugar se realiza la práctica de pesca deportiva, además de apacibles caminatas por las montañas que lo circundan.</p>
<p>El Lago Escondido debe su nombre al hecho de que viajando desde <strong>Ushuaia</strong> hacia el norte de la Isla Grande, la silueta del lago aparece sorpresivamente tras las montañas que conforman el cordón fueguino de la cordillera de los Andes.</p>
<p>Continuando la ruta, se llega al Lago Fagnano o Kami, un imponente espejo de aguas internacionales de Argentina (donde se ubica su mayor superficie) y Chile. Posee cien kilómetros de largo por seis de ancho, y a orillas del mismo la oferta de alojamiento esta conformada por una hostería, camping y cabañas desde donde se pueden efectuar cabalgatas, paseos en bicicleta y cuatriciclos entre otros. Es ideal para la pesca deportiva y el avistaje de aves locales como petreles y cauquenes.</p>
<p>El extenso lago lleva le nombre de Monseñor Fagnano quien en 1883 fue nombrado prefecto apostólico para el extremo austral de América desarrollando una gran tarea como explorador y evangelizador; protegiendo en toda ocasión a los nativos de esta área denominados Selk'nam u Onas quienes lo apodaron como "el capitán bueno".</p>
<p>Para los muy aventureros existe la opción de realizar travesías fuera de lo común a dichos lagos, con trekking a orillas del Lago Fagnano, mountain bike hasta el Lago Escondido y finalmente canotaje en este mismo espejo de agua, pudiendo saborear si uno lo desea un típico asado argentino a orillas del mismo.</p>
<p>Tanto en invierno como en verano transitar estas distancias por un serpenteante camino rodeado de bosques fueguinos y picos nevados es algo para deleitarse realmente.</p>
<h2 class="destination-subtitle">Tren del Fin del Mundo</h2>
<p>El denominado "Tren del Fin del Mundo" o "Ferrocarril Austral Fueguino", atrae no solo por su elegancia y estilo sino también por su contexto histórico relacionado con el tren de los penados del Ex Presidio de <strong>Ushuaia</strong>, al recorrer el mismo trayecto que utilizaban los penados desde principios hasta mediados en el siglo XX; y desde ya se vincula plenamente con la evolución de esta interesante y pintoresca ciudad austral.</p>
<p>El ferrocarril, de trocha angosta, es propulsado por locomotoras a vapor; y cuenta con coches elegantemente decorados, calefaccionados, y con amplios ventanales para apreciar el imponente paisaje y disfrutar plenamente de las bellezas naturales del Parque Nacional Tierra del Fuego.</p>
<p>Este ferrocarril, por su bajo impacto ambiental, es un medio ecológico único que permite llegar a una parte inaccesible del Parque Nacional Tierra del Fuego. La "Estación del Fin del Mundo", se encuentra a aproximadamente unos ocho kilómetros hacia el oeste de la ciudad de <strong>Ushuaia</strong>; desde allí parten los trenes hacia la "Estación Parque Nacional Tierra del Fuego".</p>
<p>El paseo tiene una duración aproximada de una hora y cuarenta minutos, si uno lo realiza con el ticket de ida y vuelta, caso contrario (solo de ida) son cincuenta minutos.</p>
<p>El trayecto del ferrocarril austral recorre un largo sendero al lado del Río Pipo, hasta cruzarlo en el "Puente Quemado". Luego de una curva se comienza a trepar la mayor pendiente, hasta llegar a la primera parada en la estación "Cascada La Macarena"; donde los pasajeros si lo desean pueden descender, para luego optar por subir hasta una plataforma de veinticinco metros de altura, donde puede observarse una pintoresca cascada y una interesante vista del valle. Otro camino conduce hasta la orilla del Río Pipo donde se puede apreciar la recreación de un campamento Yámana.</p>
<p>Cuando se entra al Parque Nacional Tierra del Fuego se realiza una segunda parada en Estación "Lombardich", para observar los restos de un antiguo aserradero. El ferrocarril abandona el Río Pipo y rodea un gran Turbal semejante a muchos otros diseminados por todo este territorio austral.</p>
<p>En el tramo final aparece una amplia curva donde el tren se introduce dentro de un denso bosque de cohiues y lengas, para así arribar a la estación terminal "Parque Nacional".</p>
<p>El paseo es narrado por guías bilingües (castellano e inglés), y en el interior del tren se encuentra una cómoda cafetería y bar, para saborear tortas regionales acompañadas de un exquisito chocolate. También posee una boutique, para poder adquirir bellos recuerdos de esta inolvidable visita.</p>
<h2 class="destination-subtitle">Isla de los Lobos e Isla de los Pájaros</h2>
<p>Esta es una excusión que dura de dos horas y media a tres horas, aproximadamente. Mientras se navega por la Bahía de <strong>Ushuaia</strong> y el Canal de Beagle, se pueden avistar numerosas especies de aves. Se puede pasar por el Faro Les Eclaireus para luego ver la pequeña isla con lobos marinos, la Isla de Los Pájaros con una colonia de cormoranes (cercana a las Islas Bridge) para luego retornar a <strong>Ushuaia</strong>. Otra opción es recorrer la Bahía de Lapataia hacia el oeste, donde se encuentra Puerto Arias y de allí se navega por las islas antes mencionadas para pasar luego por el Faro Les Eclaireurs y la zona donde naufragó el buque de origen alemán "Monte Cervantes" en 1930.</p>
<p>Cuando uno realiza estas diferentes excursiones, que parten todas desde la Bahía de <strong>Ushuaia</strong>, sin duda se disfruta de un espectacular paisaje sumado al encanto de los tiempos pasados.</p>
</div>
</article>
@endsection